# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parkey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'MapboxNavigation', '~> 0.19'
   pod 'MapboxSearchUI', ">= 1.0.0-beta.4", "< 2.0"

  # Pods for SearchUI-CocoaPodsDemo

end
